docs: :memo: Modelado de la base de datos
AbrahamXTS/Nojira pull request #13
Opened 2023-10-21 05:30 UTC by kirake-a

El modelado de la base de datos que usaremos a lo largo del proyecto.

closes #2

2023-10-21 16:50 UTC, Cristianpan requested changes
Te dejo unas observaciones a considerar con respecto al diagrama de entidad relación: 

- Verifica que la representación de la cardinalidad con las flechas esté correctas, ya que estas se usan para representar (1,1)
- La cardinalidad entre usuario y tarea no es adecuada, ya que una tarea solo podrá ser asignada a un usuario.
- La entidad **tarea** me parece que debería de ser una entidad débil, ya que depende de la existencia del proyecto para que esta también pueda existir. 
- La cardinalidad entre tarea y proyecto no es adecuada, ya que una tarea solo puede pertenecer a un proyecto. Esto debido al punto anterior

2023-10-21 19:46 UTC, AbrahamXTS requested changes
La tarea y el proyecto tambien deberían tener UUID como tipo de PK porque para hacer páginas relacionadas con esos usuarios, proyectos y tareas usaríamos ese identificador para la url

2023-10-21 20:16 UTC, Cristianpan requested changes
En el caso de los atributos de status y rol, de sus respectivas tablas, el tipo de dato debería de ser un varchar. De igual manera utiliza `snake_case` para todos lo atributos de las tablas. Te comparto este link que me compartió el Abraham por si te es de ayuda. [Database-Naming](https://github.com/RootSoft/Database-Naming-Convention)

2023-10-21 22:57 UTC, Cristianpan requested changes
La FK debe de tener el mismo tipo de dato que la PK

2023-10-21 23:08 UTC, Cristianpan approved these changes
Todo bien!!!

2023-10-22 03:57 UTC, AdjanyArmenta commented
En la tabla assignment el atributo rol_id hace referencia al id de la tabla role?

2023-10-22 04:06 UTC, kirake-a commented
> En la tabla assignment el atributo rol_id hace referencia al id de la tabla role?

Así es, si consideras necesario lo puedo modificar.

2023-10-22 22:28 UTC, AbrahamXTS approved these changes

2023-10-23 00:21 UTC, merged