feat: :sparkles: Generate entity schemas for Hibernate
AbrahamXTS/Nojira pull request #18
Opened 2023-10-22 06:05 UTC by AdjanyArmenta

He modificado los nombres de las tablas 'status', 'assignment' y 'role' a 'status_catalog', 'role' y 'role_status' respectivamente, con el objetivo de mejorar la comprensión de su función dentro de la base de datos
Closes issue #3

2023-10-22 22:50 UTC, AbrahamXTS approved these changes

2023-10-23 00:19 UTC, kirake-a requested changes

2023-10-23 00:19 UTC, kirake-a commented on src/main/java/com/dinamitaexplosivainsana/nojira/schemas/ProjectSchema.java
> +    private Integer id;
El tipo de dato para la clave del proyecto corresponde a un String ya que usaremos para este atributo el tipo de dato UUID, al momento de guardar una nueva tupla.

2023-10-23 00:19 UTC, kirake-a commented on src/main/java/com/dinamitaexplosivainsana/nojira/schemas/TaskSchema.java
> +    private Integer id;
El tipo de dato para la clave de la tarea corresponde a un String ya que usaremos para este atributo el tipo de dato UUID, al momento de guardar una nueva tupla.

2023-10-23 00:19 UTC, kirake-a commented on src/main/java/com/dinamitaexplosivainsana/nojira/schemas/UserSchema.java
>  public class UserSchema {
El tipo de dato para la clave del usuario corresponde a un String ya que usaremos para este atributo el tipo de dato UUID, al momento de guardar una nueva tupla.

2023-10-23 02:23 UTC, kirake-a approved these changes
Por mi parte ya está todo correcto.

2023-10-23 02:41 UTC, merged